# Generated by Django 5.1.6 on 2025-05-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('accessory', 'Accessory'), ('part', 'Part'), ('oil', 'Oil'), ('cleaner', 'Cleaner')], default='accessory', max_length=20),
        ),
    ]
